[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
noise = "0.7"
rand = "0.8"
image = "0.23"

[dev-dependencies]
assert_approx_eq = "1.1.0"
rstest = "0.9.0"